name: deploy-model-training-pipeline

on:
  workflow_dispatch:
    inputs:
      customer_id:
        type: string
        description: "Customer Specifier"
      model_id:
        type: string
        description: "Model Specifier (e.g. ppe)"
      datasets:
        type: string
        description: "Comma-separaterd list of Datasets (e.g. 2023-09-SET-01,2023-09-SET-02,2023-10-SET-01) - leave blank to process all datasets"
      env_name:
        type: string
        default: azureml:yolov8-train-env@latest

jobs:
  set-env-branch:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: set-prod-branch
        if: ${{ github.ref == 'refs/heads/main'}}
        run: echo "config_env=config-infra-prod.yml" >> $GITHUB_ENV;
      - id: set-dev-branch
        name: set-dev-branch
        if: ${{ github.ref != 'refs/heads/main'}}
        run: echo "config_env=config-infra-dev.yml" >> $GITHUB_ENV;
      - id: set-output-defaults
        name: set-output-defaults
        run: |
          echo "config-file=$config_env" >> $GITHUB_OUTPUT;

  get-config:
    needs: set-env-branch
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file}}

  run-model-training-pipeline:
    needs: get-config
    uses: ./.github/workflows/run-training-pipeline.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      customer_id: ${{ github.event.inputs.customer_id }}
      model_id: ${{ github.event.inputs.model_id }}
      parameters_file: mlops/azureml/pipeline/pipeline.yml
      datasets: ${{ github.event.inputs.datasets }}
      env_name: ${{inputs.env_name}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
