name: register-azureml-environment

on:
  workflow_dispatch:

jobs:
  set-env-branch:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: set-prod-branch
        if: ${{ github.ref == 'refs/heads/main'}}
        run: echo "config_env=config-infra-prod.yml" >> $GITHUB_ENV;
      - id: set-dev-branch
        name: set-dev-branch
        if: ${{ github.ref != 'refs/heads/main'}}
        run: echo "config_env=config-infra-dev.yml" >> $GITHUB_ENV;
      - id: set-output-defaults
        name: set-output-defaults
        run: |
          echo "config-file=$config_env" >> $GITHUB_OUTPUT;

  get-config:
    needs: set-env-branch
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file}}

  register-environment:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      environment_file: mlops/azureml/environment/train-env.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
